version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: packages/nextjs/Dockerfile
    image: botanix-ln-webapp:latest  
    ports:
      - "3000:3000"
    environment:
      - WEBSOCKET_URL=ws://localhost:3003 
      # Websocket server URL set to your domain if hosted example "wss://yourdomain.com/websocket" 
    depends_on:
      - server
    restart: always

  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    image: botanix-ln-server:latest
    ports:
      - "3003:3003"
    restart: always

